# Generated by Django 5.0.6 on 2024-06-29 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-date_created']},
        ),
    ]
